import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { AppCard, EmptyState, IconAction, palette, StatusPill } from "@/components/neuro-ui";
import { useDepartment } from "@/lib/department-store";
import type { TeamNotification } from "@/lib/department-model";
import { useAppLanguage } from "@/lib/language";

export default function NotificationsScreen() {
  const { data, session, markNotificationRead, markAllNotificationsRead } = useDepartment();
  const { language, isRTL, localize } = useAppLanguage();
  const userId = session?.userId ?? "";
  const notifications = (data.notifications ?? []).filter((item) => item.recipientIds.includes(userId));
  const unreadCount = notifications.filter((item) => !item.readByUserIds.includes(userId)).length;
  const openNotification = (item: TeamNotification) => { markNotificationRead(item.id); router.push({ pathname: "/team/[id]", params: { id: item.teamId } }); };
  const renderItem = ({ item }: { item: TeamNotification }) => {
    const unread = !item.readByUserIds.includes(userId);
    return <Pressable onPress={() => openNotification(item)} style={({ pressed }) => pressed && { opacity: 0.78 }}><AppCard style={[styles.card, unread && styles.unreadCard]}><View style={[styles.cardHead, { flexDirection: isRTL ? "row-reverse" : "row" }]}><View style={[styles.iconShell, { backgroundColor: item.type === "consultation" ? palette.paleTeal : "#FFF3D4" }]}><MaterialIcons name={item.type === "consultation" ? "forum" : "hotel"} size={20} color={item.type === "consultation" ? palette.teal : palette.gold} /></View><View style={styles.headText}><Text style={[styles.teamName, align(isRTL)]}>{item.teamName}</Text><Text style={[styles.time, align(isRTL)]}>{localize(item.createdAt)}</Text></View>{unread ? <View style={styles.unreadDot} /> : null}</View><Text style={[styles.notificationTitle, align(isRTL)]}>{localize(item.title)}</Text><Text style={[styles.message, align(isRTL)]}>{localize(item.message)}</Text><View style={[styles.cardFoot, { flexDirection: isRTL ? "row-reverse" : "row" }]}><StatusPill label={item.type === "consultation" ? "استشارة" : "حالة منوّمة"} tone={item.type === "consultation" ? "teal" : "gold"} /><View style={[styles.openLink, { flexDirection: isRTL ? "row-reverse" : "row" }]}><Text style={[styles.openLinkText, { writingDirection: isRTL ? "rtl" : "ltr" }]}>{localize("فتح غرفة الفريق")}</Text><MaterialIcons name={isRTL ? "arrow-back" : "arrow-forward"} size={15} color={palette.navy} /></View></View></AppCard></Pressable>;
  };
  return <View style={styles.page}><View style={[styles.header, { flexDirection: isRTL ? "row" : "row-reverse" }]}><IconAction icon={isRTL ? "arrow-forward" : "arrow-back"} label="رجوع" onPress={() => router.back()} /><View style={styles.titleWrap}><Text style={[styles.title, align(isRTL)]}>{localize("الإشعارات")}</Text><Text style={[styles.subtitle, align(isRTL)]}>{unreadCount > 0 ? language === "en" ? `${unreadCount} unread alerts` : `${unreadCount} تنبيهات غير مقروءة` : language === "en" ? "All alerts are read" : "جميع التنبيهات مقروءة"}</Text></View>{unreadCount > 0 ? <Pressable onPress={markAllNotificationsRead} style={styles.readAll}><Text style={[styles.readAllText, { writingDirection: isRTL ? "rtl" : "ltr" }]}>{localize("قراءة الكل")}</Text></Pressable> : <View style={styles.readAll} />}</View><FlatList data={notifications} renderItem={renderItem} keyExtractor={(item) => item.id} contentContainerStyle={notifications.length ? styles.list : styles.emptyList} ListEmptyComponent={<EmptyState icon="notifications-none" text="لا توجد إشعارات جديدة لفرقك العلاجية." />} showsVerticalScrollIndicator={false} /></View>;
}

function align(isRTL: boolean) { return { writingDirection: isRTL ? "rtl" as const : "ltr" as const, textAlign: isRTL ? "right" as const : "left" as const }; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: palette.canvas, paddingHorizontal: 18 }, header: { paddingTop: 20, paddingBottom: 16, alignItems: "center", gap: 12 }, titleWrap: { flex: 1 }, title: { color: palette.ink, fontSize: 21, fontWeight: "900" }, subtitle: { color: palette.muted, fontSize: 12, marginTop: 3 }, readAll: { minWidth: 56, alignItems: "flex-end" }, readAllText: { color: palette.navy, fontSize: 12, fontWeight: "800" }, list: { gap: 10, paddingBottom: 25 }, emptyList: { flexGrow: 1, justifyContent: "center" }, card: { padding: 15 }, unreadCard: { borderColor: "#93C5FD", backgroundColor: "#FCFEFF" }, cardHead: { alignItems: "center", gap: 10 }, iconShell: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center" }, headText: { flex: 1 }, teamName: { color: palette.ink, fontSize: 13, fontWeight: "900" }, time: { color: palette.muted, fontSize: 10, marginTop: 2 }, unreadDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: palette.urgent }, notificationTitle: { color: palette.ink, fontSize: 15, fontWeight: "900", marginTop: 13 }, message: { color: palette.muted, fontSize: 12, lineHeight: 18, marginTop: 5 }, cardFoot: { marginTop: 13, paddingTop: 11, borderTopWidth: 1, borderTopColor: palette.line, justifyContent: "space-between", alignItems: "center" }, openLink: { alignItems: "center", gap: 4 }, openLinkText: { color: palette.navy, fontSize: 11, fontWeight: "800" } });
