import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { AppCard, EmptyState, IconAction, palette, StatusPill } from "@/components/neuro-ui";
import { useDepartment } from "@/lib/department-store";
import type { TeamNotification } from "@/lib/department-model";

export default function NotificationsScreen() {
  const { data, session, markNotificationRead, markAllNotificationsRead } = useDepartment();
  const userId = session?.userId ?? "";
  const notifications = (data.notifications ?? []).filter((item) => item.recipientIds.includes(userId));
  const unreadCount = notifications.filter((item) => !item.readByUserIds.includes(userId)).length;
  const openNotification = (item: TeamNotification) => {
    markNotificationRead(item.id);
    router.push({ pathname: "/team/[id]", params: { id: item.teamId } });
  };
  const renderItem = ({ item }: { item: TeamNotification }) => {
    const unread = !item.readByUserIds.includes(userId);
    return <Pressable onPress={() => openNotification(item)} style={({ pressed }) => pressed && { opacity: 0.78 }}><AppCard style={[styles.card, unread && styles.unreadCard]}><View style={styles.cardHead}><View style={[styles.iconShell, { backgroundColor: item.type === "consultation" ? palette.paleTeal : "#FFF3D4" }]}><MaterialIcons name={item.type === "consultation" ? "forum" : "hotel"} size={20} color={item.type === "consultation" ? palette.teal : palette.gold} /></View><View style={styles.headText}><Text style={styles.teamName}>{item.teamName}</Text><Text style={styles.time}>{item.createdAt}</Text></View>{unread ? <View style={styles.unreadDot} /> : null}</View><Text style={styles.notificationTitle}>{item.title}</Text><Text style={styles.message}>{item.message}</Text><View style={styles.cardFoot}><StatusPill label={item.type === "consultation" ? "استشارة" : "حالة منوّمة"} tone={item.type === "consultation" ? "teal" : "gold"} /><View style={styles.openLink}><Text style={styles.openLinkText}>فتح غرفة الفريق</Text><MaterialIcons name="arrow-back" size={15} color={palette.navy} /></View></View></AppCard></Pressable>;
  };
  return <View style={styles.page}><View style={styles.header}><IconAction icon="arrow-forward" label="رجوع" onPress={() => router.back()} /><View style={styles.titleWrap}><Text style={styles.title}>الإشعارات</Text><Text style={styles.subtitle}>{unreadCount > 0 ? `${unreadCount} تنبيهات غير مقروءة` : "جميع التنبيهات مقروءة"}</Text></View>{unreadCount > 0 ? <Pressable onPress={markAllNotificationsRead} style={styles.readAll}><Text style={styles.readAllText}>قراءة الكل</Text></Pressable> : <View style={styles.readAll} />}</View><FlatList data={notifications} renderItem={renderItem} keyExtractor={(item) => item.id} contentContainerStyle={notifications.length ? styles.list : styles.emptyList} ListEmptyComponent={<EmptyState icon="notifications-none" text="لا توجد إشعارات جديدة لفرقك العلاجية." />} showsVerticalScrollIndicator={false} /></View>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: palette.canvas, paddingHorizontal: 18 }, header: { paddingTop: 20, paddingBottom: 16, flexDirection: "row", alignItems: "center", gap: 12 }, titleWrap: { flex: 1 }, title: { color: palette.ink, fontSize: 21, fontWeight: "900", textAlign: "right", writingDirection: "rtl" }, subtitle: { color: palette.muted, fontSize: 12, marginTop: 3, textAlign: "right", writingDirection: "rtl" }, readAll: { minWidth: 56, alignItems: "flex-end" }, readAllText: { color: palette.navy, fontSize: 12, fontWeight: "800", writingDirection: "rtl" }, list: { gap: 10, paddingBottom: 25 }, emptyList: { flexGrow: 1, justifyContent: "center" }, card: { padding: 15 }, unreadCard: { borderColor: "#93C5FD", backgroundColor: "#FCFEFF" }, cardHead: { flexDirection: "row-reverse", alignItems: "center", gap: 10 }, iconShell: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center" }, headText: { flex: 1 }, teamName: { color: palette.ink, fontSize: 13, fontWeight: "900", textAlign: "right", writingDirection: "rtl" }, time: { color: palette.muted, fontSize: 10, textAlign: "right", writingDirection: "rtl", marginTop: 2 }, unreadDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: palette.urgent }, notificationTitle: { color: palette.ink, fontSize: 15, fontWeight: "900", textAlign: "right", writingDirection: "rtl", marginTop: 13 }, message: { color: palette.muted, fontSize: 12, lineHeight: 18, textAlign: "right", writingDirection: "rtl", marginTop: 5 }, cardFoot: { marginTop: 13, paddingTop: 11, borderTopWidth: 1, borderTopColor: palette.line, flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, openLink: { flexDirection: "row-reverse", alignItems: "center", gap: 4 }, openLinkText: { color: palette.navy, fontSize: 11, fontWeight: "800", writingDirection: "rtl" } });
