import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { AppCard, palette, PrimaryButton, SectionTitle, StatusPill } from "@/components/neuro-ui";
import { useDepartment } from "@/lib/department-store";
import { roleLabels } from "@/lib/department-model";

export default function ProfileScreen() {
  const { session, data, signOut } = useDepartment();
  const user = data.users.find((item) => item.id === session?.userId);
  const teamNames = user?.teamIds.map((id) => data.teams.find((team) => team.id === id)?.name).filter(Boolean).join(" · ");
  const leave = async () => { await signOut(); router.replace("/login"); };
  const confirmSignOut = () => Alert.alert("تسجيل الخروج", "هل تريد إنهاء جلسة العرض الحالية؟", [{ text: "إلغاء", style: "cancel" }, { text: "تسجيل الخروج", style: "destructive", onPress: leave }]);
  return <View style={styles.page}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.close}><MaterialIcons name="close" size={22} color={palette.navy} /></Pressable><Text style={styles.title}>حسابي</Text><View style={{ width: 40 }} /></View><View style={styles.profileHead}><View style={styles.avatar}><Text style={styles.avatarText}>{session?.name.slice(0, 1)}</Text></View><Text style={styles.name}>{session?.name}</Text><StatusPill label={session?.role ? roleLabels[session.role] : "مستخدم"} tone={session?.role === "admin" ? "gold" : "blue"} /></View><SectionTitle title="الانتماءات" /><AppCard><View style={styles.detailRow}><MaterialIcons name="groups" size={21} color={palette.navy} /><View style={styles.detailCopy}><Text style={styles.detailLabel}>الفرق العلاجية</Text><Text style={styles.detailValue}>{teamNames || "لا توجد فرق مسندة"}</Text></View></View><View style={styles.divider} /><View style={styles.detailRow}><MaterialIcons name="security" size={21} color={palette.teal} /><View style={styles.detailCopy}><Text style={styles.detailLabel}>نطاق الوصول</Text><Text style={styles.detailValue}>{session?.role === "admin" ? "إدارة القسم والفرق والقوائم" : "السجلات والفرق المسندة"}</Text></View></View></AppCard><SectionTitle title="الخصوصية" /><AppCard><View style={styles.notice}><MaterialIcons name="privacy-tip" size={21} color={palette.gold} /><Text style={styles.noticeText}>يحفظ هذا النموذج بيانات العرض محلياً فقط. لا تُدخل بيانات المرضى الحقيقية قبل تفعيل الدخول المؤسسي وربط قاعدة البيانات الآمنة.</Text></View></AppCard><View style={styles.logout}><PrimaryButton label="تسجيل الخروج" onPress={confirmSignOut} icon="logout" tone="light" /></View></View>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: palette.canvas, paddingHorizontal: 18 }, header: { paddingTop: 22, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, close: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.line, alignItems: "center", justifyContent: "center" }, title: { color: palette.ink, fontSize: 20, fontWeight: "900", writingDirection: "rtl" }, profileHead: { alignItems: "center", marginTop: 22 }, avatar: { width: 78, height: 78, borderRadius: 27, backgroundColor: palette.navy, alignItems: "center", justifyContent: "center", borderWidth: 5, borderColor: "#D9EEF8" }, avatarText: { color: "#FFFFFF", fontSize: 32, fontWeight: "900", writingDirection: "rtl" }, name: { color: palette.ink, fontSize: 20, fontWeight: "900", writingDirection: "rtl", marginTop: 11 }, detailRow: { flexDirection: "row-reverse", gap: 12, alignItems: "center" }, detailCopy: { flex: 1 }, detailLabel: { color: palette.muted, fontSize: 11, textAlign: "right", writingDirection: "rtl" }, detailValue: { color: palette.ink, fontSize: 13, fontWeight: "800", lineHeight: 19, textAlign: "right", writingDirection: "rtl", marginTop: 3 }, divider: { height: 1, backgroundColor: palette.line, marginVertical: 14 }, notice: { flexDirection: "row-reverse", gap: 9, alignItems: "flex-start" }, noticeText: { color: "#75530D", flex: 1, fontSize: 12, lineHeight: 19, textAlign: "right", writingDirection: "rtl" }, logout: { marginTop: 24 } });
