import { useState } from "react";
import { ActivityIndicator, Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { AppCard, IconAction, palette, PrimaryButton, SectionTitle, StatusPill } from "@/components/neuro-ui";
import type { PatientCase } from "@/lib/department-model";
import type { DepartmentSession } from "@/lib/department-session";
import { requestMedicalReportDraft } from "@/lib/medical-report-draft-api";
import { exportApprovedMedicalReport } from "@/lib/medical-report-draft-export";
import { MEDICAL_REPORT_SECTION_KEYS, medicalReportSectionLabels, type MedicalReportDraft } from "@/shared/medical-report-draft";

export function MedicalReportDraftAction({ patient, session, language, isRTL }: { patient: PatientCase; session: DepartmentSession | null; language: "ar" | "en"; isRTL: boolean }) {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [draft, setDraft] = useState<MedicalReportDraft | null>(null);
  const [approved, setApproved] = useState(false);
  const [reportLanguage, setReportLanguage] = useState<"ar" | "en">(language);
  const labels = medicalReportSectionLabels(reportLanguage);
  const title = language === "en" ? "Medical report" : "تقرير طبي";
  const generate = async () => {
    setLoading(true);
    try {
      const result = await requestMedicalReportDraft({ patient, session, language: reportLanguage });
      setDraft(result.draft); setApproved(false); setOpen(true);
    } catch {
      Alert.alert(language === "en" ? "Draft unavailable" : "تعذر إنشاء المسودة", language === "en" ? "An approved central department connection is required. No report was generated." : "يلزم اتصال مركزي بحساب قسم معتمد. لم يتم إنشاء أي تقرير.");
    } finally { setLoading(false); }
  };
  const updateSection = (key: keyof MedicalReportDraft, value: string) => setDraft((current) => current ? { ...current, [key]: value } : current);
  const approve = () => { setApproved(true); Alert.alert(language === "en" ? "Draft approved" : "تم اعتماد المسودة", language === "en" ? "You can now export the reviewed PDF." : "يمكنك الآن تصدير ملف PDF بعد المراجعة."); };
  const exportPdf = async () => {
    if (!draft || !approved) return;
    try {
      const result = await exportApprovedMedicalReport({ patient, draft, language: reportLanguage, template: reportLanguage === "en" ? "formal-english" : "standard", approvedBy: session?.name ?? (language === "en" ? "Approved clinician" : "الطبيب المعتمد") });
      Alert.alert(language === "en" ? "Report ready" : "التقرير جاهز", result === "downloaded" ? (language === "en" ? "The PDF download is ready." : "أصبح تنزيل PDF جاهزًا.") : (language === "en" ? "Choose where to save or share the reviewed PDF." : "اختر مكان حفظ أو مشاركة PDF بعد المراجعة."));
    } catch { Alert.alert(language === "en" ? "Export unavailable" : "تعذر التصدير", language === "en" ? "The reviewed PDF could not be prepared." : "لم نتمكن من تجهيز PDF بعد المراجعة."); }
  };

  return <><SectionTitle title={title} /><AppCard style={styles.card}><View style={[styles.row, direction(isRTL)]}><View style={styles.icon}><MaterialIcons name="description" size={21} color="#FFFFFF" /></View><View style={styles.flex}><Text style={[styles.title, align(isRTL)]}>{language === "en" ? "AI-assisted medical report draft" : "مسودة تقرير طبي بمساعدة الذكاء الاصطناعي"}</Text><Text style={[styles.text, align(isRTL)]}>{language === "en" ? "Uses documented file data only. Clinician review and approval are required before export." : "تستخدم البيانات الموثقة في الملف فقط. تتطلب مراجعة واعتماد الطبيب قبل التصدير."}</Text></View></View><Text style={[styles.templateLabel, align(isRTL)]}>{language === "en" ? "Report language and print template" : "لغة التقرير ونموذج الطباعة"}</Text><View style={[styles.templateRow, direction(isRTL)]}><Pressable onPress={() => setReportLanguage("en")} style={[styles.templateChoice, reportLanguage === "en" && styles.templateChoiceActive]}><Text style={[styles.templateChoiceText, reportLanguage === "en" && styles.templateChoiceTextActive]}>English · Official</Text></Pressable><Pressable onPress={() => setReportLanguage("ar")} style={[styles.templateChoice, reportLanguage === "ar" && styles.templateChoiceActive]}><Text style={[styles.templateChoiceText, reportLanguage === "ar" && styles.templateChoiceTextActive]}>العربية · نموذج موحد</Text></Pressable></View><Pressable onPress={generate} disabled={loading} style={({ pressed }) => [styles.generate, pressed && styles.pressed, loading && styles.disabled]} accessibilityLabel={language === "en" ? "Generate medical report draft" : "إنشاء مسودة تقرير طبي"}>{loading ? <ActivityIndicator color="#FFFFFF" /> : <MaterialIcons name="auto-awesome" size={19} color="#FFFFFF" />}<Text style={styles.generateText}>{loading ? (language === "en" ? "Preparing draft…" : "جارٍ تجهيز المسودة…") : (language === "en" ? "Generate review draft" : "إنشاء مسودة للمراجعة")}</Text></Pressable></AppCard>
    <Modal visible={open} animationType="slide" onRequestClose={() => setOpen(false)}><View style={styles.modalPage}><View style={[styles.modalHeader, direction(isRTL)]}><IconAction icon={isRTL ? "arrow-forward" : "arrow-back"} label={language === "en" ? "Close" : "إغلاق"} onPress={() => setOpen(false)} /><Text style={[styles.modalTitle, align(isRTL)]}>{language === "en" ? "Review medical report" : "مراجعة التقرير الطبي"}</Text><View style={styles.headerSpace} /></View><ScrollView contentContainerStyle={styles.content}><View style={[styles.notice, direction(isRTL)]}><MaterialIcons name="health-and-safety" size={20} color={palette.navy} /><Text style={[styles.noticeText, align(isRTL)]}>{language === "en" ? "AI-assisted draft. Verify every section against the patient file; complete or correct it before approval. This tool does not make diagnoses or clinical recommendations." : "مسودة مساعدة بالذكاء الاصطناعي. راجع كل قسم مقابل ملف المريض واستكمله أو صححه قبل الاعتماد. لا تصدر الأداة تشخيصات أو توصيات سريرية."}</Text></View>{draft ? MEDICAL_REPORT_SECTION_KEYS.map((key) => <View key={key} style={styles.field}><Text style={[styles.label, align(isRTL)]}>{labels[key]}</Text><TextInput value={draft[key]} onChangeText={(value) => updateSection(key, value)} multiline textAlignVertical="top" textAlign={isRTL ? "right" : "left"} style={[styles.input, { writingDirection: isRTL ? "rtl" : "ltr", textAlign: isRTL ? "right" : "left" }]} /></View>) : null}<View style={[styles.reviewState, direction(isRTL)]}><StatusPill label={approved ? (language === "en" ? "Clinician reviewed" : "تمت المراجعة") : (language === "en" ? "Review required" : "مراجعة مطلوبة")} tone={approved ? "teal" : "gold"} /><Text style={[styles.reviewText, align(isRTL)]}>{approved ? (language === "en" ? "The PDF may be exported." : "يمكن تصدير PDF الآن.") : (language === "en" ? "PDF export remains locked until you approve the reviewed draft." : "يبقى تصدير PDF مقفلاً حتى تعتمد المسودة بعد المراجعة.")}</Text></View><PrimaryButton label={language === "en" ? "Approve reviewed draft" : "اعتماد المسودة بعد المراجعة"} icon="verified" onPress={approve} /><Pressable onPress={exportPdf} disabled={!approved} style={[styles.export, !approved && styles.exportDisabled]}><MaterialIcons name="picture-as-pdf" size={20} color={approved ? "#FFFFFF" : palette.muted} /><Text style={[styles.exportText, !approved && styles.exportTextDisabled]}>{language === "en" ? "Export approved PDF" : "تصدير PDF المعتمد"}</Text></Pressable></ScrollView></View></Modal></>;
}

function direction(isRTL: boolean) { return { flexDirection: isRTL ? "row-reverse" as const : "row" as const }; }
function align(isRTL: boolean) { return { textAlign: isRTL ? "right" as const : "left" as const, writingDirection: isRTL ? "rtl" as const : "ltr" as const }; }

const styles = StyleSheet.create({ card: { marginTop: 10, padding: 14, borderColor: "#D8DCFA", backgroundColor: "#FCFCFF" }, row: { gap: 10, alignItems: "flex-start" }, icon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: palette.navy }, flex: { flex: 1 }, title: { color: palette.ink, fontSize: 14, fontWeight: "900" }, text: { color: palette.muted, fontSize: 11, lineHeight: 17, marginTop: 4 }, templateLabel: { color: palette.ink, fontSize: 11, fontWeight: "800", marginTop: 14, marginBottom: 7 }, templateRow: { gap: 8 }, templateChoice: { flex: 1, minHeight: 40, borderRadius: 12, borderWidth: 1, borderColor: palette.line, backgroundColor: "#FFFFFF", justifyContent: "center", alignItems: "center", paddingHorizontal: 8 }, templateChoiceActive: { backgroundColor: palette.paleBlue, borderColor: palette.navy }, templateChoiceText: { color: palette.muted, fontSize: 10, fontWeight: "800" }, templateChoiceTextActive: { color: palette.navy }, generate: { minHeight: 45, marginTop: 14, paddingHorizontal: 13, borderRadius: 13, backgroundColor: palette.navy, alignItems: "center", justifyContent: "center", gap: 8, flexDirection: "row" }, generateText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, pressed: { opacity: 0.78 }, disabled: { opacity: 0.65 }, modalPage: { flex: 1, backgroundColor: palette.canvas }, modalHeader: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 12, justifyContent: "space-between", alignItems: "center", borderBottomWidth: 1, borderBottomColor: palette.line }, modalTitle: { flex: 1, color: palette.ink, fontSize: 17, fontWeight: "900" }, headerSpace: { width: 40 }, content: { padding: 18, paddingBottom: 38 }, notice: { gap: 8, padding: 12, borderRadius: 14, backgroundColor: palette.paleBlue, alignItems: "flex-start" }, noticeText: { flex: 1, color: palette.navy, fontSize: 11, lineHeight: 17, fontWeight: "700" }, field: { marginTop: 14 }, label: { color: palette.ink, fontSize: 13, fontWeight: "900", marginBottom: 6 }, input: { minHeight: 88, borderWidth: 1, borderColor: palette.line, borderRadius: 13, backgroundColor: "#FFFFFF", color: palette.ink, paddingHorizontal: 11, paddingTop: 10, fontSize: 12, lineHeight: 19 }, reviewState: { gap: 9, alignItems: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.line, padding: 11, borderRadius: 13, marginTop: 16, marginBottom: 12 }, reviewText: { flex: 1, color: palette.muted, fontSize: 10, lineHeight: 15 }, export: { minHeight: 46, borderRadius: 13, backgroundColor: palette.teal, marginTop: 10, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 }, exportDisabled: { backgroundColor: palette.paleBlue, borderWidth: 1, borderColor: palette.line }, exportText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, exportTextDisabled: { color: palette.muted } });
