import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { AppCard, MetricCard, NotificationBell, palette, PrimaryButton, SectionTitle, StatusPill } from "@/components/neuro-ui";
import { useDepartment } from "@/lib/department-store";
import { getDashboardSummary } from "@/lib/department-model";
import { useAppLanguage } from "@/lib/language";

export default function HomeScreen() {
  const { data, session } = useDepartment();
  const { language, isRTL, t } = useAppLanguage();
  const summary = getDashboardSummary(data);
  const firstReport = data.reports.find((item) => item.status !== "مكتمل") ?? data.reports[0];
  const firstSurgery = data.surgeries[0];
  const unreadNotifications = (data.notifications ?? []).filter((item) => item.recipientIds.includes(session?.userId ?? "") && !item.readByUserIds.includes(session?.userId ?? "")).length;

  return <ScrollView style={styles.page} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={[styles.header, { flexDirection: isRTL ? "row-reverse" : "row" }]}><View><Text style={[styles.hello, { writingDirection: isRTL ? "rtl" : "ltr", textAlign: isRTL ? "right" : "left" }]}>{t("morning")}</Text><Text style={[styles.name, { writingDirection: isRTL ? "rtl" : "ltr", textAlign: isRTL ? "right" : "left" }]}>{session?.name}</Text><Text style={[styles.date, { writingDirection: isRTL ? "rtl" : "ltr", textAlign: isRTL ? "right" : "left" }]}>{language === "en" ? "Wednesday, 26 August" : "الأربعاء، 26 أغسطس"}</Text></View><View style={[styles.headerActions, { flexDirection: isRTL ? "row-reverse" : "row" }]}><Pressable accessibilityRole="button" accessibilityLabel={language === "en" ? "My profile" : "ملفي الشخصي"} onPress={() => router.push("/profile")} style={({ pressed }) => [styles.profileShortcut, pressed && { opacity: 0.72 }]}><MaterialIcons name="person" size={21} color={palette.navy} /></Pressable><NotificationBell count={unreadNotifications} onPress={() => router.push("/notifications")} /></View></View>
    <AppCard style={[styles.banner, { flexDirection: isRTL ? "row-reverse" : "row" }]}><View style={styles.bannerIcon}><MaterialIcons name="medical-services" color="#FFFFFF" size={23} /></View><View style={[styles.bannerCopy, { alignItems: isRTL ? "flex-end" : "flex-start" }]}><Text style={[styles.bannerTitle, { writingDirection: isRTL ? "rtl" : "ltr" }]}>{t("operationalHub")}</Text><Text style={[styles.bannerText, { writingDirection: isRTL ? "rtl" : "ltr", textAlign: isRTL ? "right" : "left" }]}>{t("operationalCopy")}</Text></View></AppCard>
    <View style={[styles.metricsRow, { flexDirection: isRTL ? "row-reverse" : "row" }]}><MetricCard icon="description" value={summary.openReports} label={t("openRequests")} tone="red" /><MetricCard icon="local-hospital" value={summary.surgeriesToday} label={t("todaySurgeries")} tone="blue" /></View>
    <View style={[styles.metricsRow, { flexDirection: isRTL ? "row-reverse" : "row" }]}><MetricCard icon="hotel" value={summary.admittedCases} label={t("admittedCases")} tone="teal" /><MetricCard icon="groups" value={summary.activeTeams} label={t("activeTeams")} tone="gold" /></View>
    <SectionTitle title={t("quickActions")} /><View style={[styles.quickActions, { flexDirection: isRTL ? "row-reverse" : "row" }]}><QuickAction icon="add-comment" label={language === "en" ? "New consultation" : "استشارة جديدة"} onPress={() => router.push("/consultation" as any)} /><QuickAction icon="description" label={t("newReport")} onPress={() => router.push("/(tabs)/reports")} /><QuickAction icon="groups" label={t("teamRooms")} onPress={() => router.push("/(tabs)/teams")} /><QuickAction icon="notifications" label={t("notifications")} onPress={() => router.push("/notifications")} /></View><View style={[styles.quickActions, { flexDirection: isRTL ? "row-reverse" : "row", marginTop: 8 }]}><QuickAction icon="person" label={language === "en" ? "My profile" : "حسابي"} onPress={() => router.push("/profile")} /></View>
    <SectionTitle title={t("priorityNow")} action={t("viewReports")} onPress={() => router.push("/(tabs)/reports")} />
    {firstReport ? <AppCard><View style={[styles.cardTop, { flexDirection: isRTL ? "row-reverse" : "row" }]}><StatusPill label={firstReport.priority} tone={firstReport.priority === "عاجل" ? "red" : firstReport.priority === "عادي" ? "blue" : "gold"} /><Text style={styles.code}>{firstReport.patientCode}</Text></View><Text style={[styles.cardTitle, { writingDirection: isRTL ? "rtl" : "ltr", textAlign: isRTL ? "right" : "left" }]}>{firstReport.title}</Text><View style={[styles.rowDetail, { flexDirection: isRTL ? "row-reverse" : "row" }]}><Text style={[styles.detail, { writingDirection: isRTL ? "rtl" : "ltr", textAlign: isRTL ? "right" : "left" }]}>{firstReport.requester}</Text><Text style={[styles.detail, { writingDirection: isRTL ? "rtl" : "ltr", textAlign: isRTL ? "right" : "left" }]}>{language === "en" ? `Due: ${firstReport.dueAt}` : `الاستحقاق: ${firstReport.dueAt}`}</Text></View><PrimaryButton label={language === "en" ? "Open request" : "فتح الطلب"} icon={isRTL ? "arrow-back" : "arrow-forward"} onPress={() => router.push("/(tabs)/reports")} tone="light" /></AppCard> : null}
    <SectionTitle title={language === "en" ? "First surgery today" : "أول عملية اليوم"} action={t("viewSchedule")} onPress={() => router.push("/(tabs)/schedule")} />
    {firstSurgery ? <AppCard><View style={styles.operationTop}><View><Text style={styles.operationTime}>{firstSurgery.time}</Text><Text style={styles.operationRoom}>{firstSurgery.room}</Text></View><StatusPill label={firstSurgery.status} tone={firstSurgery.status === "مؤكد" ? "teal" : "gold"} /></View><Text style={styles.cardTitle}>{firstSurgery.procedure}</Text><Text style={styles.detail}>{firstSurgery.patientCode} · {firstSurgery.surgeon}</Text></AppCard> : null}
  </ScrollView>;
}

function QuickAction({ icon, label, onPress }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; label: string; onPress: () => void }) { const { isRTL } = useAppLanguage(); return <Pressable onPress={onPress} style={({ pressed }) => [styles.quickAction, pressed && { opacity: 0.72 }]}><MaterialIcons name={icon} size={20} color={palette.navy} /><Text style={[styles.quickLabel, { writingDirection: isRTL ? "rtl" : "ltr" }]}>{label}</Text></Pressable>; }

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: palette.canvas }, content: { padding: 18, paddingBottom: 32 }, header: { flexDirection: "row-reverse", alignItems: "flex-start", justifyContent: "space-between", paddingTop: 8 }, headerActions: { alignItems: "center", gap: 8 }, profileShortcut: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.line, alignItems: "center", justifyContent: "center" }, hello: { color: palette.muted, fontSize: 14 }, name: { color: palette.ink, fontSize: 22, fontWeight: "900", marginTop: 3 }, date: { color: palette.muted, fontSize: 12, marginTop: 4 }, banner: { marginTop: 20, flexDirection: "row-reverse", backgroundColor: palette.navy, borderColor: palette.navy, gap: 12 }, bannerIcon: { height: 44, width: 44, borderRadius: 15, backgroundColor: "#FFFFFF2C", alignItems: "center", justifyContent: "center" }, bannerCopy: { flex: 1, alignItems: "flex-end" }, bannerTitle: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" }, bannerText: { color: "#D8EEF9", fontSize: 12, lineHeight: 18, textAlign: "right", marginTop: 4 }, metricsRow: { flexDirection: "row-reverse", gap: 10, marginTop: 10 }, quickActions: { flexDirection: "row-reverse", gap: 8, marginTop: -1, marginBottom: 4 }, quickAction: { flex: 1, minHeight: 70, backgroundColor: "#FFFFFF", borderColor: palette.line, borderWidth: 1, borderRadius: 16, alignItems: "center", justifyContent: "center", gap: 6 }, quickLabel: { color: palette.navy, fontSize: 10, fontWeight: "800", textAlign: "center", writingDirection: "rtl" }, cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, code: { color: palette.muted, fontWeight: "800", fontSize: 12 }, cardTitle: { color: palette.ink, fontSize: 16, fontWeight: "900", writingDirection: "rtl", textAlign: "right", marginTop: 12, marginBottom: 8 }, rowDetail: { flexDirection: "row-reverse", justifyContent: "space-between", marginBottom: 14 }, detail: { color: palette.muted, fontSize: 12, writingDirection: "rtl", textAlign: "right" }, operationTop: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, operationTime: { color: palette.navy, fontSize: 25, fontWeight: "900", textAlign: "right" }, operationRoom: { color: palette.muted, fontSize: 12, writingDirection: "rtl", textAlign: "right", marginTop: 2 },
});
