import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { Alert, FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { AppCard, palette, PrimaryButton, SectionTitle, StatusPill } from "@/components/neuro-ui";
import { useDepartment } from "@/lib/department-store";
import type { MedicalReport, ReportPriority } from "@/lib/department-model";
import { useAppLanguage } from "@/lib/language";

function priorityTone(priority: ReportPriority): "red" | "blue" | "gold" { return priority === "عاجل" ? "red" : priority === "عادي" ? "blue" : "gold"; }
function align(isRTL: boolean) { return { writingDirection: isRTL ? "rtl" as const : "ltr" as const, textAlign: isRTL ? "right" as const : "left" as const }; }

export default function ReportsScreen() {
  const { data, advanceReport, addReport } = useDepartment();
  const { language, isRTL, localize } = useAppLanguage();
  const [modalVisible, setModalVisible] = useState(false);
  const [patientFileNumber, setPatientFileNumber] = useState("");
  const [title, setTitle] = useState("");
  const [priority, setPriority] = useState<ReportPriority>("عادي");
  const create = () => {
    if (!patientFileNumber.trim() || !title.trim()) { Alert.alert(localize("بيانات ناقصة"), language === "en" ? "Enter the medical record number and report title." : "أدخل رقم الملف وعنوان التقرير."); return; }
    addReport({ patientCode: patientFileNumber, title, priority }); setPatientFileNumber(""); setTitle(""); setPriority("عادي"); setModalVisible(false);
  };
  const renderItem = ({ item }: { item: MedicalReport }) => <AppCard style={styles.reportCard}><View style={[styles.reportHead, { flexDirection: isRTL ? "row-reverse" : "row" }]}><View><Text style={styles.reportCode}>{item.patientCode}</Text><Text style={[styles.created, align(isRTL)]}>{item.createdAt}</Text></View><StatusPill label={item.priority} tone={priorityTone(item.priority)} /></View><Text style={[styles.reportTitle, align(isRTL)]}>{item.title}</Text><Text style={[styles.requester, align(isRTL)]}>{language === "en" ? `Requested by: ${item.requester}` : `الطلب من: ${item.requester}`}</Text><View style={[styles.reportFoot, { flexDirection: isRTL ? "row-reverse" : "row" }]}><Text style={styles.due}>{language === "en" ? `Due: ${item.dueAt}` : `الاستحقاق: ${item.dueAt}`}</Text><Pressable onPress={() => advanceReport(item.id)} style={styles.statusButton}><Text style={styles.statusButtonText}>{item.status === "جديد" ? (language === "en" ? "Start preparation" : "بدء الإعداد") : item.status === "قيد الإعداد" ? (language === "en" ? "Complete report" : "إتمام التقرير") : localize("مكتمل")}</Text></Pressable></View></AppCard>;
  return <View style={styles.page}><View style={[styles.header, { flexDirection: isRTL ? "row-reverse" : "row" }]}><View style={styles.headerCopy}><Text style={[styles.title, align(isRTL)]}>{language === "en" ? "Report requests" : "طلبات التقارير"}</Text><Text style={[styles.subtitle, align(isRTL)]}>{language === "en" ? `${data.reports.filter((item) => item.status !== "مكتمل").length} requests need follow-up` : `${data.reports.filter((item) => item.status !== "مكتمل").length} طلبات تحتاج متابعة`}</Text></View><View style={[styles.headerActions, { flexDirection: isRTL ? "row-reverse" : "row" }]}><Pressable onPress={() => router.push("/shift-report-dashboard")} style={[styles.dashboard, { marginHorizontal: 0 }]} accessibilityLabel={language === "en" ? "Monthly on-call dashboard" : "لوحة معلومات المناوبات الشهرية"}><MaterialIcons name="insights" color={palette.teal} size={21} /></Pressable><Pressable onPress={() => router.push("/shift-report")} style={styles.shiftReport} accessibilityLabel={language === "en" ? "Daily shift report" : "تقرير المناوبة اليومي"}><MaterialIcons name="assignment" color={palette.navy} size={21} /></Pressable><Pressable onPress={() => setModalVisible(true)} style={styles.add}><MaterialIcons name="add" color="#FFFFFF" size={25} /></Pressable></View></View><FlatList data={data.reports} keyExtractor={(item) => item.id} renderItem={renderItem} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} />
    <Modal visible={modalVisible} transparent animationType="slide" onRequestClose={() => setModalVisible(false)}><View style={styles.modalShade}><View style={styles.sheet}><View style={styles.handle} /><SectionTitle title={language === "en" ? "New report request" : "طلب تقرير جديد"} /><Text style={[styles.label, align(isRTL)]}>{language === "en" ? "Medical record no." : "رقم الملف"}</Text><TextInput value={patientFileNumber} onChangeText={setPatientFileNumber} placeholder="KSMC-000000" placeholderTextColor="#9FB3C8" style={[styles.input, align(isRTL)]} textAlign={isRTL ? "right" : "left"} /><Text style={[styles.label, align(isRTL)]}>{language === "en" ? "Report title" : "عنوان التقرير"}</Text><TextInput value={title} onChangeText={setTitle} placeholder={language === "en" ? "e.g. Discharge report" : "مثال: تقرير خروج طبي"} placeholderTextColor="#9FB3C8" style={[styles.input, align(isRTL)]} textAlign={isRTL ? "right" : "left"} /><Text style={[styles.label, align(isRTL)]}>{language === "en" ? "Priority" : "الأولوية"}</Text><View style={[styles.choiceRow, { flexDirection: isRTL ? "row-reverse" : "row" }]}>{(["عاجل", "عادي", "متابعة"] as ReportPriority[]).map((option) => <Pressable key={option} onPress={() => setPriority(option)} style={[styles.choice, priority === option && styles.choiceSelected]}><Text style={styles.choiceText}>{localize(option)}</Text></Pressable>)}</View><PrimaryButton label={language === "en" ? "Add request" : "إضافة الطلب"} onPress={create} icon="add" /></View></View></Modal>
  </View>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: palette.canvas, paddingHorizontal: 18 }, header: { paddingTop: 24, paddingBottom: 16, justifyContent: "space-between", alignItems: "center" }, headerCopy: { flex: 1 }, headerActions: { gap: 8, alignItems: "center" }, title: { color: palette.ink, fontSize: 24, fontWeight: "900" }, subtitle: { color: palette.muted, fontSize: 13, marginTop: 4 }, add: { height: 44, width: 44, borderRadius: 15, backgroundColor: palette.navy, alignItems: "center", justifyContent: "center" }, shiftReport: { height: 44, width: 44, borderRadius: 15, backgroundColor: palette.paleGold, borderWidth: 1, borderColor: "#EBC97B", alignItems: "center", justifyContent: "center" }, dashboard: { height: 44, width: 44, borderRadius: 15, backgroundColor: "#EAF8F5", borderWidth: 1, borderColor: "#9CDDD2", alignItems: "center", justifyContent: "center" }, list: { paddingBottom: 24, gap: 10 }, reportCard: { padding: 15 }, reportHead: { justifyContent: "space-between" }, reportCode: { color: palette.ink, fontSize: 13, fontWeight: "900" }, created: { color: palette.muted, fontSize: 11, marginTop: 3 }, reportTitle: { color: palette.ink, fontSize: 16, fontWeight: "900", marginTop: 12 }, requester: { color: palette.muted, fontSize: 12, marginTop: 5 }, reportFoot: { borderTopColor: palette.line, borderTopWidth: 1, marginTop: 13, paddingTop: 11, justifyContent: "space-between", alignItems: "center" }, due: { color: palette.gold, fontSize: 11, fontWeight: "700" }, statusButton: { backgroundColor: palette.paleBlue, paddingHorizontal: 11, paddingVertical: 7, borderRadius: 10 }, statusButtonText: { color: palette.navy, fontSize: 11, fontWeight: "800" }, modalShade: { flex: 1, justifyContent: "flex-end", backgroundColor: "#102A4370" }, sheet: { backgroundColor: "#FFFFFF", padding: 20, paddingBottom: 36, borderTopLeftRadius: 28, borderTopRightRadius: 28 }, handle: { alignSelf: "center", width: 40, height: 4, borderRadius: 2, backgroundColor: palette.line, marginBottom: 2 }, label: { color: palette.ink, fontSize: 13, fontWeight: "800", marginBottom: 6 }, input: { borderWidth: 1, borderColor: palette.line, borderRadius: 13, minHeight: 48, paddingHorizontal: 12, color: palette.ink, marginBottom: 12 }, choiceRow: { gap: 8, marginBottom: 16 }, choice: { flex: 1, alignItems: "center", paddingVertical: 11, borderColor: palette.line, borderWidth: 1, borderRadius: 12 }, choiceSelected: { backgroundColor: palette.paleBlue, borderColor: palette.navy }, choiceText: { color: palette.ink, fontSize: 12, fontWeight: "800" } });
