import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { Alert, FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { AppCard, palette, PrimaryButton, SectionTitle, StatusPill } from "@/components/neuro-ui";
import { useDepartment } from "@/lib/department-store";
import type { MedicalReport, ReportPriority } from "@/lib/department-model";

function priorityTone(priority: ReportPriority): "red" | "blue" | "gold" { return priority === "عاجل" ? "red" : priority === "عادي" ? "blue" : "gold"; }

export default function ReportsScreen() {
  const { data, advanceReport, addReport } = useDepartment();
  const [modalVisible, setModalVisible] = useState(false);
  const [patientCode, setPatientCode] = useState("");
  const [title, setTitle] = useState("");
  const [priority, setPriority] = useState<ReportPriority>("عادي");
  const create = () => {
    if (!patientCode.trim() || !title.trim()) { Alert.alert("بيانات ناقصة", "أدخل رمز الحالة وعنوان التقرير."); return; }
    addReport({ patientCode, title, priority }); setPatientCode(""); setTitle(""); setPriority("عادي"); setModalVisible(false);
  };
  const renderItem = ({ item }: { item: MedicalReport }) => <AppCard style={styles.reportCard}><View style={styles.reportHead}><View><Text style={styles.reportCode}>{item.patientCode}</Text><Text style={styles.created}>{item.createdAt}</Text></View><StatusPill label={item.priority} tone={priorityTone(item.priority)} /></View><Text style={styles.reportTitle}>{item.title}</Text><Text style={styles.requester}>الطلب من: {item.requester}</Text><View style={styles.reportFoot}><Text style={styles.due}>الاستحقاق: {item.dueAt}</Text><Pressable onPress={() => advanceReport(item.id)} style={({ pressed }) => [styles.statusButton, pressed && { opacity: 0.7 }]}><Text style={styles.statusButtonText}>{item.status === "جديد" ? "بدء الإعداد" : item.status === "قيد الإعداد" ? "إتمام التقرير" : "مكتمل"}</Text></Pressable></View></AppCard>;
  return <View style={styles.page}><View style={styles.header}><View><Text style={styles.title}>طلبات التقارير</Text><Text style={styles.subtitle}>{data.reports.filter((item) => item.status !== "مكتمل").length} طلبات تحتاج متابعة</Text></View><Pressable onPress={() => setModalVisible(true)} style={({ pressed }) => [styles.add, pressed && { opacity: 0.8 }]}><MaterialIcons name="add" color="#FFFFFF" size={25} /></Pressable></View><FlatList data={data.reports} keyExtractor={(item) => item.id} renderItem={renderItem} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} />
    <Modal visible={modalVisible} transparent animationType="slide" onRequestClose={() => setModalVisible(false)}><View style={styles.modalShade}><View style={styles.sheet}><View style={styles.handle} /><SectionTitle title="طلب تقرير جديد" /><Text style={styles.label}>رمز الحالة</Text><TextInput value={patientCode} onChangeText={setPatientCode} placeholder="مثال: NS-2050" placeholderTextColor="#9FB3C8" style={styles.input} textAlign="right" /><Text style={styles.label}>عنوان التقرير</Text><TextInput value={title} onChangeText={setTitle} placeholder="مثال: تقرير خروج طبي" placeholderTextColor="#9FB3C8" style={styles.input} textAlign="right" /><Text style={styles.label}>الأولوية</Text><View style={styles.choiceRow}><Pressable onPress={() => setPriority("عاجل")} style={[styles.choice, priority === "عاجل" && styles.choiceSelected]}><Text style={styles.choiceText}>عاجل</Text></Pressable><Pressable onPress={() => setPriority("عادي")} style={[styles.choice, priority === "عادي" && styles.choiceSelected]}><Text style={styles.choiceText}>عادي</Text></Pressable><Pressable onPress={() => setPriority("متابعة")} style={[styles.choice, priority === "متابعة" && styles.choiceSelected]}><Text style={styles.choiceText}>متابعة</Text></Pressable></View><PrimaryButton label="إضافة الطلب" onPress={create} icon="add" /></View></View></Modal>
  </View>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: palette.canvas, paddingHorizontal: 18 }, header: { paddingTop: 24, paddingBottom: 16, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, title: { color: palette.ink, fontSize: 24, fontWeight: "900", textAlign: "right", writingDirection: "rtl" }, subtitle: { color: palette.muted, fontSize: 13, marginTop: 4, writingDirection: "rtl", textAlign: "right" }, add: { height: 44, width: 44, borderRadius: 15, backgroundColor: palette.navy, alignItems: "center", justifyContent: "center" }, list: { paddingBottom: 24, gap: 10 }, reportCard: { padding: 15 }, reportHead: { flexDirection: "row-reverse", justifyContent: "space-between" }, reportCode: { color: palette.ink, fontSize: 13, fontWeight: "900", textAlign: "right" }, created: { color: palette.muted, fontSize: 11, marginTop: 3, writingDirection: "rtl", textAlign: "right" }, reportTitle: { color: palette.ink, fontSize: 16, fontWeight: "900", marginTop: 12, writingDirection: "rtl", textAlign: "right" }, requester: { color: palette.muted, fontSize: 12, marginTop: 5, writingDirection: "rtl", textAlign: "right" }, reportFoot: { borderTopColor: palette.line, borderTopWidth: 1, marginTop: 13, paddingTop: 11, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, due: { color: palette.gold, fontSize: 11, fontWeight: "700", writingDirection: "rtl" }, statusButton: { backgroundColor: palette.paleBlue, paddingHorizontal: 11, paddingVertical: 7, borderRadius: 10 }, statusButtonText: { color: palette.navy, fontSize: 11, fontWeight: "800", writingDirection: "rtl" }, modalShade: { flex: 1, justifyContent: "flex-end", backgroundColor: "#102A4370" }, sheet: { backgroundColor: "#FFFFFF", padding: 20, paddingBottom: 36, borderTopLeftRadius: 28, borderTopRightRadius: 28 }, handle: { alignSelf: "center", width: 40, height: 4, borderRadius: 2, backgroundColor: palette.line, marginBottom: 2 }, label: { color: palette.ink, fontSize: 13, fontWeight: "800", textAlign: "right", writingDirection: "rtl", marginBottom: 6 }, input: { borderWidth: 1, borderColor: palette.line, borderRadius: 13, minHeight: 48, paddingHorizontal: 12, color: palette.ink, marginBottom: 12, writingDirection: "rtl" }, choiceRow: { flexDirection: "row-reverse", gap: 8, marginBottom: 16 }, choice: { flex: 1, alignItems: "center", paddingVertical: 11, borderColor: palette.line, borderWidth: 1, borderRadius: 12 }, choiceSelected: { backgroundColor: palette.paleBlue, borderColor: palette.navy }, choiceText: { color: palette.ink, fontSize: 12, fontWeight: "800", writingDirection: "rtl" } });
