import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { Alert, FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { AppCard, palette, PrimaryButton, SectionTitle, StatusPill } from "@/components/neuro-ui";
import { useDepartment } from "@/lib/department-store";
import type { Shift, Surgery } from "@/lib/department-model";

export default function ScheduleScreen() {
  const { data, session, addShift, addSurgery } = useDepartment();
  const [section, setSection] = useState<"operations" | "shifts">("operations");
  const [modal, setModal] = useState<"shift" | "surgery" | null>(null);
  const [field1, setField1] = useState(""); const [field2, setField2] = useState(""); const [field3, setField3] = useState("");
  const isAdmin = session?.role === "admin";
  const create = () => { if (!field1 || !field2 || !field3) { Alert.alert("بيانات ناقصة", "أكمل الحقول الظاهرة أولاً."); return; } if (modal === "shift") addShift({ clinician: field1, period: field2 === "مسائي" || field2 === "ليلي" ? field2 : "صباحي", team: field3 }); else addSurgery({ patientCode: field1, procedure: field2, surgeon: field3 }); setField1(""); setField2(""); setField3(""); setModal(null); };
  const renderOperation = ({ item }: { item: Surgery }) => <AppCard style={styles.card}><View style={styles.operationHead}><View><Text style={styles.time}>{item.time}</Text><Text style={styles.room}>{item.room}</Text></View><StatusPill label={item.status} tone={item.status === "مؤكد" ? "teal" : "gold"} /></View><Text style={styles.cardTitle}>{item.procedure}</Text><Text style={styles.cardMeta}>{item.patientCode} · {item.surgeon}</Text></AppCard>;
  const renderShift = ({ item }: { item: Shift }) => <AppCard style={styles.card}><View style={styles.shiftHead}><View style={styles.period}><MaterialIcons name="schedule" size={18} color={palette.navy} /><Text style={styles.periodText}>{item.period}</Text></View><Text style={styles.shiftDate}>{item.date}</Text></View><Text style={styles.cardTitle}>{item.clinician}</Text><Text style={styles.cardMeta}>{item.role} · {item.team}</Text><Text style={styles.location}>{item.location}</Text></AppCard>;
  const dataToShow = section === "operations" ? data.surgeries : data.shifts;
  return <View style={styles.page}><View style={styles.header}><View><Text style={styles.title}>الجداول التشغيلية</Text><Text style={styles.subtitle}>تنسيق يوم القسم، الأربعاء 26 أغسطس</Text></View>{isAdmin ? <Pressable style={styles.add} onPress={() => setModal(section === "operations" ? "surgery" : "shift")}><MaterialIcons name="add" color="#FFFFFF" size={25} /></Pressable> : null}</View><View style={styles.tabs}><Pressable onPress={() => setSection("operations")} style={[styles.tab, section === "operations" && styles.activeTab]}><Text style={[styles.tabText, section === "operations" && styles.activeTabText]}>العمليات</Text></Pressable><Pressable onPress={() => setSection("shifts")} style={[styles.tab, section === "shifts" && styles.activeTab]}><Text style={[styles.tabText, section === "shifts" && styles.activeTabText]}>المناوبات</Text></Pressable></View><FlatList data={dataToShow as (Surgery | Shift)[]} keyExtractor={(item) => item.id} renderItem={section === "operations" ? renderOperation as any : renderShift as any} contentContainerStyle={styles.list} />
    <Modal visible={modal !== null} transparent animationType="slide" onRequestClose={() => setModal(null)}><View style={styles.modalShade}><View style={styles.sheet}><View style={styles.handle} /><SectionTitle title={modal === "surgery" ? "إضافة عملية" : "إضافة مناوبة"} /><Text style={styles.label}>{modal === "surgery" ? "رمز الحالة" : "اسم الطبيب"}</Text><TextInput value={field1} onChangeText={setField1} textAlign="right" style={styles.input} placeholderTextColor="#9FB3C8" placeholder={modal === "surgery" ? "مثال: NS-2050" : "الاسم الكامل"} /><Text style={styles.label}>{modal === "surgery" ? "نوع العملية" : "الفترة (صباحي / مسائي / ليلي)"}</Text><TextInput value={field2} onChangeText={setField2} textAlign="right" style={styles.input} placeholderTextColor="#9FB3C8" placeholder={modal === "surgery" ? "وصف الإجراء" : "صباحي"} /><Text style={styles.label}>{modal === "surgery" ? "الجراح" : "الفريق"}</Text><TextInput value={field3} onChangeText={setField3} textAlign="right" style={styles.input} placeholderTextColor="#9FB3C8" placeholder={modal === "surgery" ? "الاسم الكامل" : "اسم الفريق"} /><PrimaryButton label="حفظ في الجدول" onPress={create} icon="save" /></View></View></Modal>
  </View>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: palette.canvas, paddingHorizontal: 18 }, header: { paddingTop: 24, paddingBottom: 16, flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, title: { color: palette.ink, fontSize: 24, fontWeight: "900", textAlign: "right", writingDirection: "rtl" }, subtitle: { color: palette.muted, fontSize: 12, marginTop: 4, writingDirection: "rtl", textAlign: "right" }, add: { height: 44, width: 44, borderRadius: 15, backgroundColor: palette.navy, alignItems: "center", justifyContent: "center" }, tabs: { backgroundColor: "#E9F1F7", padding: 4, borderRadius: 15, flexDirection: "row-reverse" }, tab: { flex: 1, alignItems: "center", paddingVertical: 10, borderRadius: 11 }, activeTab: { backgroundColor: "#FFFFFF", shadowColor: "#486581", shadowOpacity: 0.12, shadowRadius: 4, elevation: 1 }, tabText: { color: palette.muted, fontSize: 13, fontWeight: "800", writingDirection: "rtl" }, activeTabText: { color: palette.navy }, list: { paddingTop: 12, gap: 10, paddingBottom: 25 }, card: { padding: 15 }, operationHead: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, time: { color: palette.navy, fontSize: 24, fontWeight: "900", textAlign: "right" }, room: { color: palette.muted, fontSize: 11, textAlign: "right", writingDirection: "rtl" }, cardTitle: { color: palette.ink, fontSize: 16, fontWeight: "900", textAlign: "right", writingDirection: "rtl", marginTop: 12 }, cardMeta: { color: palette.muted, fontSize: 12, textAlign: "right", writingDirection: "rtl", marginTop: 5 }, shiftHead: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, period: { flexDirection: "row-reverse", gap: 5, alignItems: "center", backgroundColor: palette.paleBlue, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 9 }, periodText: { color: palette.navy, fontSize: 12, fontWeight: "800", writingDirection: "rtl" }, shiftDate: { color: palette.muted, fontSize: 12, writingDirection: "rtl" }, location: { color: palette.gold, fontSize: 11, marginTop: 9, writingDirection: "rtl", textAlign: "right" }, modalShade: { flex: 1, justifyContent: "flex-end", backgroundColor: "#102A4370" }, sheet: { backgroundColor: "#FFFFFF", padding: 20, paddingBottom: 36, borderTopLeftRadius: 28, borderTopRightRadius: 28 }, handle: { alignSelf: "center", width: 40, height: 4, borderRadius: 2, backgroundColor: palette.line, marginBottom: 2 }, label: { color: palette.ink, fontSize: 13, fontWeight: "800", textAlign: "right", writingDirection: "rtl", marginBottom: 6 }, input: { borderWidth: 1, borderColor: palette.line, borderRadius: 13, minHeight: 48, paddingHorizontal: 12, color: palette.ink, marginBottom: 12, writingDirection: "rtl" } });
