import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { AppCard, palette, StatusPill } from "@/components/neuro-ui";
import { useDepartment } from "@/lib/department-store";
import type { CareTeam } from "@/lib/department-model";
import { useAppLanguage } from "@/lib/language";
import { hasUnreadPatientUpdate } from "@/lib/patient-file-updates";
import { useSafeAreaInsets } from "react-native-safe-area-context";

export default function TeamsScreen() {
  const { data, session } = useDepartment();
  const { language, isRTL, localize } = useAppLanguage();
  const insets = useSafeAreaInsets();
  const renderItem = ({ item }: { item: CareTeam }) => {
    const hasAccess = Boolean(session);
    const admitted = item.cases.filter((medicalCase) => medicalCase.status === "منوّم").length;
    const unreadUpdates = item.cases.filter((patient) => hasUnreadPatientUpdate(patient, session?.userId)).length;
    return <Pressable onPress={() => router.push({ pathname: "/team/[id]", params: { id: item.id } })} style={({ pressed }) => pressed && { opacity: 0.82 }}><AppCard style={styles.card}><View style={[styles.cardHead, { flexDirection: isRTL ? "row-reverse" : "row" }]}><View style={[styles.ident, { flexDirection: isRTL ? "row-reverse" : "row" }]}><View style={[styles.teamMark, { backgroundColor: item.color }]}><Text style={styles.teamMarkText}>{item.shortName}</Text></View><View><Text style={[styles.teamName, align(isRTL)]}>{item.name}</Text><Text style={[styles.teamLead, align(isRTL)]}>{language === "en" ? `Team lead: ${item.lead}` : `قائد الفريق: ${item.lead}`}</Text></View></View><MaterialIcons name={isRTL ? "chevron-left" : "chevron-right"} size={24} color={palette.muted} /></View><View style={[styles.stats, { flexDirection: isRTL ? "row-reverse" : "row" }]}><View style={[styles.stat, { flexDirection: isRTL ? "row-reverse" : "row" }]}><MaterialIcons name="hotel" size={16} color={palette.teal} /><Text style={[styles.statText, { writingDirection: isRTL ? "rtl" : "ltr" }]}>{language === "en" ? `${admitted} admitted cases` : `${admitted} حالات منوّمة`}</Text></View><View style={[styles.stat, { flexDirection: isRTL ? "row-reverse" : "row" }]}><MaterialIcons name="forum" size={16} color={palette.navy} /><Text style={[styles.statText, { writingDirection: isRTL ? "rtl" : "ltr" }]}>{language === "en" ? `${item.consultations.length} consultations` : `${item.consultations.length} استشارات`}</Text></View></View><View style={[styles.access, { flexDirection: isRTL ? "row-reverse" : "row" }]}><View style={[styles.accessPills, { flexDirection: isRTL ? "row-reverse" : "row" }]}><StatusPill label={hasAccess ? (language === "en" ? "Can update records" : "يمكنه تحديث الملفات") : (language === "en" ? "View only" : "عرض فقط")} tone={hasAccess ? "teal" : "grey"} />{unreadUpdates ? <StatusPill label={language === "en" ? `${unreadUpdates} new update${unreadUpdates === 1 ? "" : "s"}` : `${unreadUpdates} تحديث جديد`} tone="gold" /> : null}</View><Text style={[styles.memberCount, { writingDirection: isRTL ? "rtl" : "ltr" }]}>{language === "en" ? `${item.memberIds.length} members` : `${item.memberIds.length} أعضاء`}</Text></View></AppCard></Pressable>;
  };
  return <View style={styles.page}><View style={[styles.header, { paddingTop: Math.max(12, insets.top + 8) }]}><Text style={[styles.title, align(isRTL)]}>{localize("الفرق العلاجية")}</Text><Text style={[styles.subtitle, align(isRTL)]}>{localize("غرف متابعة الحالات والاستشارات لكل فريق")}</Text></View><FlatList data={data.teams} renderItem={renderItem} keyExtractor={(item) => item.id} contentContainerStyle={[styles.list, { paddingBottom: Math.max(25, insets.bottom + 16) }]} showsVerticalScrollIndicator={false} /></View>;
}

function align(isRTL: boolean) { return { writingDirection: isRTL ? "rtl" as const : "ltr" as const, textAlign: isRTL ? "right" as const : "left" as const }; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: palette.canvas, paddingHorizontal: 18 }, header: { paddingTop: 24, paddingBottom: 16 }, title: { color: palette.ink, fontSize: 24, fontWeight: "900" }, subtitle: { color: palette.muted, fontSize: 13, marginTop: 5 }, list: { gap: 11, paddingBottom: 25 }, card: { padding: 15 }, cardHead: { justifyContent: "space-between", alignItems: "center" }, ident: { gap: 11, alignItems: "center", flex: 1 }, teamMark: { height: 46, width: 46, borderRadius: 15, alignItems: "center", justifyContent: "center" }, teamMarkText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, teamName: { color: palette.ink, fontSize: 15, fontWeight: "900" }, teamLead: { color: palette.muted, fontSize: 11, marginTop: 4 }, stats: { gap: 16, borderTopWidth: 1, borderTopColor: palette.line, marginTop: 14, paddingTop: 12 }, stat: { alignItems: "center", gap: 5 }, statText: { color: palette.muted, fontSize: 11 }, access: { marginTop: 12, justifyContent: "space-between", alignItems: "center", gap: 8 }, accessPills: { alignItems: "center", gap: 6, flex: 1, flexWrap: "wrap" }, memberCount: { color: palette.muted, fontSize: 11 } });
